## Plantilla de preprocesado

In [1]:
#numpy, libreria de python para el tratamiento de numeros (arrays: +,-,*,/)
#matplotlib, libreria para graficar
#pandas, libreria para manipular datos (excel)

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
#Importar el dataset
dataset=pd.read_csv('Resources/Data.csv')

In [3]:
#X son las variables independientes del algoritmo (Country, Age, Salary)
#Y es la variable que se quiere precedir (Purchased=Comprado)
#Observaciones son la filas
dataset

Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes

In [4]:
type(dataset)

pandas.core.frame.DataFrame

In [5]:
x=dataset.iloc[:,:-1]

In [6]:
y=dataset.iloc[:,3]

In [7]:
x

Country   Age   Salary
0   France  44.0  72000.0
1    Spain  27.0  48000.0
2  Germany  30.0  54000.0
3    Spain  38.0  61000.0
4  Germany  40.0      NaN
5   France  35.0  58000.0
6    Spain   NaN  52000.0
7   France  48.0  79000.0
8  Germany  50.0  83000.0
9   France  37.0  67000.0

In [8]:
y

0     No
1    Yes
2     No
3     No
4    Yes
5    Yes
6     No
7    Yes
8     No
9    Yes
Name: Purchased, dtype: object

In [9]:
#TRATAMIENTO DE LOS NAN
#Datos faltantes (NaN)
#Resolver los NaN los antes posible
#Tecnicas para llenar datos NaN:
    #Eliminar la observacion (muy drastico y no recomendable)
    #Remplazar por la media (primera opcion)

#from sklearn.preprocessing import Imputer #antigua version
from sklearn.impute import SimpleImputer

In [10]:
#axis=0 es por columna; axis=1 es por fila
imputer=SimpleImputer(missing_values=np.nan, strategy='mean')#Calculo de la media para cada columna

imputer=imputer.fit(x.iloc[:,1:3]) #Ajustar los valores NaN. Ajustar con los valores de la media cada columna
x.iloc[:,1:3]=imputer.transform(x.iloc[:,1:3])#Aplicar los valores ajustados al dataframe

#imputer=imputer.fit(x[:,1:3])
#x[:,1:3]=imputer.fit_transform(x[:,1:3])

In [11]:
type(x)

pandas.core.frame.DataFrame

In [12]:
x

Country        Age        Salary
0   France  44.000000  72000.000000
1    Spain  27.000000  48000.000000
2  Germany  30.000000  54000.000000
3    Spain  38.000000  61000.000000
4  Germany  40.000000  63777.777778
5   France  35.000000  58000.000000
6    Spain  38.777778  52000.000000
7   France  48.000000  79000.000000
8  Germany  50.000000  83000.000000
9   France  37.000000  67000.000000

In [13]:
#DATOS CATEGORICOS

#Existen dos tipos de variables: Categoricas y Numerica
    #Categoricas (texto)
        #Nominal (A,B,C)
        #Ordinal (I,II,III)
    #Numericas (numero)
        #Discretas (1,2,3)
        #Continuas (1.1, 2.5, 12.3)

#Los datos categoricos son columnas que en lugar de contener un numero contiene valores para catologar (etiqueta)
#En un modelo no se puede meter datos categoricos (no se pueden sumar datos categoricos)
#Existen variables categoricas:
    #nominal (no importa el orden)
    #ordinal (importa el orden)
#from sklearn.preprocessing import LabelEncoder, OneHotEncoder


In [14]:
#NOTA: Para transformar una variable categorica nominal a numero ya no es necesario utilizar laberEnconder() y luego OneHotEncoder()
#labelEncoder_x=LabelEncoder()

#LabelEncoder, codifa texto a numero
#OneHotEncoder, variable dummy, es una forma de traducir una categoria que no tiene un orden (nominal)

#x.iloc[:,0]=labelEncoder_x.fit_transform(x.iloc[:,0])

In [15]:
#El resultado de la codificacion no es correcto
#Cuando se habla de paises no existen comparaciones de cual es mayor o menor
#x

In [16]:
#Variable X - LabelEncoder y Dummies Columns

from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

ct_x=ColumnTransformer(
    [('one_hot_encoder', OneHotEncoder(categories='auto'),[0])],
    remainder='passthrough'
)

x=np.array(ct_x.fit_transform(x),dtype=np.float)

C:\Users\VIC\AppData\Local\Temp/ipykernel_22252/3819086835.py:11: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  x=np.array(ct_x.fit_transform(x),dtype=np.float)


In [17]:
x

array([[1.00000000e+00, 0.00000000e+00, 0.00000000e+00, 4.40000000e+01,
        7.20000000e+04],
       [0.00000000e+00, 0.00000000e+00, 1.00000000e+00, 2.70000000e+01,
        4.80000000e+04],
       [0.00000000e+00, 1.00000000e+00, 0.00000000e+00, 3.00000000e+01,
        5.40000000e+04],
       [0.00000000e+00, 0.00000000e+00, 1.00000000e+00, 3.80000000e+01,
        6.10000000e+04],
       [0.00000000e+00, 1.00000000e+00, 0.00000000e+00, 4.00000000e+01,
        6.37777778e+04],
       [1.00000000e+00, 0.00000000e+00, 0.00000000e+00, 3.50000000e+01,
        5.80000000e+04],
       [0.00000000e+00, 0.00000000e+00, 1.00000000e+00, 3.87777778e+01,
        5.20000000e+04],
       [1.00000000e+00, 0.00000000e+00, 0.00000000e+00, 4.80000000e+01,
        7.90000000e+04],
       [0.00000000e+00, 1.00000000e+00, 0.00000000e+00, 5.00000000e+01,
        8.30000000e+04],
       [1.00000000e+00, 0.00000000e+00, 0.00000000e+00, 3.70000000e+01,
        6.70000000e+04]])

In [18]:
#Variable Y - LabelEncoder

from sklearn.preprocessing import LabelEncoder
labelEncoder_y=LabelEncoder()
y=labelEncoder_y.fit_transform(y)

In [19]:
y

array([0, 1, 0, 0, 1, 1, 0, 1, 0, 1])

In [20]:
#DATASET DE TRAINIG Y TEST

#Training, para entrenar el algoritmo. Entrenar un modelo que sea capaz de predecir la variable dependiente
#Test, para probar el algoritmo
#Overfiting, el algoritmo memoriza
#Normalmente 20% o 30% para testing

from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.2, random_state= 0) #randon_state=Para que siempre devuleva el mismo resultado, es cualquier numero

In [21]:
x_train

array([[0.00000000e+00, 1.00000000e+00, 0.00000000e+00, 4.00000000e+01,
        6.37777778e+04],
       [1.00000000e+00, 0.00000000e+00, 0.00000000e+00, 3.70000000e+01,
        6.70000000e+04],
       [0.00000000e+00, 0.00000000e+00, 1.00000000e+00, 2.70000000e+01,
        4.80000000e+04],
       [0.00000000e+00, 0.00000000e+00, 1.00000000e+00, 3.87777778e+01,
        5.20000000e+04],
       [1.00000000e+00, 0.00000000e+00, 0.00000000e+00, 4.80000000e+01,
        7.90000000e+04],
       [0.00000000e+00, 0.00000000e+00, 1.00000000e+00, 3.80000000e+01,
        6.10000000e+04],
       [1.00000000e+00, 0.00000000e+00, 0.00000000e+00, 4.40000000e+01,
        7.20000000e+04],
       [1.00000000e+00, 0.00000000e+00, 0.00000000e+00, 3.50000000e+01,
        5.80000000e+04]])

In [22]:
y_train

array([1, 1, 1, 0, 1, 0, 0, 1])

In [23]:
x_test

array([[0.0e+00, 1.0e+00, 0.0e+00, 3.0e+01, 5.4e+04],
       [0.0e+00, 1.0e+00, 0.0e+00, 5.0e+01, 8.3e+04]])

In [25]:
y_test

array([0, 0])

In [29]:
#ESCALAR DATOS

#Escalar significar normalizar los valores para que no existan diferencia de valores de rangos
#Si no se escala para el algoritmo algunos valores pasan desapercibidos
#El escalado evita que unas variables dominen sobre otras
#El escalado es importante para que algoritmo asigne un peso
#Si hay una variable con rango de valores mas grandes que otra variable, entonces escalar

#### Estandarizacion (dividir entre la desviacion estandar)
#Le resta la media y lo divide por la desviacion estandar
#genera una campana de gauss
#genera valores entorno a la media
#los valores estaran cercanos a 0, los extremos tendran valores 1 pico o 3 pico
    # x estandarizado = x - media(x)/desviacion estandar(x)

#### Normalizacion (dividir de forma normalito)
#resta el minimo y divide el maximo menos el minimo
#los valores se transforman entre 0 y 1
    # x normalizado = x - minimo(x) / maximo(x) - minimo(x)

#### Es necesario escalar las variables dummy
#Ambas razones son validas
#No existen ventjas al escalar las variables dummy
#En ambos casos convergen de la misma manera
#Si,
    #para que todas las variables queden en el mismo rango.
    #Por coerencias
    #Se pierde la nocion de pertenencia de las variables dummy (0,1,2 a 0.145, 0.454, 0.4545)
#No,
    #Las variables dummy mantienen sus valores de pertenencia
    #Son mas legibles

####Escalar la variable Y
#Algoritmo de clasificacion
    #En este caso no es necesario escalar
    #Solo se quire clasificar si compra o no compra
#Algoritmos de prediccion
    #Regresion lineal
    #Es recomendable escalar

from sklearn.preprocessing import StandardScaler

sc_x=StandardScaler() #Crear el escalador estandar
x_train=sc_x.fit_transform(x_train) #escalar automaticamente el conjunto de entrenamiento  'x_train'. Fit y Transform
x_test=sc_x.transform(x_test) #el conjunto de test se va escalar con la misma transformacion que el escalador haya detectado apartir del conjunto de entrenamentio. Se trata que todo el mundo quede escalado con la misma formular. Solo transform

In [30]:
x_train

array([[-1.        ,  2.64575131, -0.77459667,  0.26306757,  0.12381479],
       [ 1.        , -0.37796447, -0.77459667, -0.25350148,  0.46175632],
       [-1.        , -0.37796447,  1.29099445, -1.97539832, -1.53093341],
       [-1.        , -0.37796447,  1.29099445,  0.05261351, -1.11141978],
       [ 1.        , -0.37796447, -0.77459667,  1.64058505,  1.7202972 ],
       [-1.        , -0.37796447,  1.29099445, -0.0813118 , -0.16751412],
       [ 1.        , -0.37796447, -0.77459667,  0.95182631,  0.98614835],
       [ 1.        , -0.37796447, -0.77459667, -0.59788085, -0.48214934]])

In [32]:
x_test

array([[-1.        ,  2.64575131, -0.77459667, -1.45882927, -0.90166297],
       [-1.        ,  2.64575131, -0.77459667,  1.98496442,  2.13981082]])